// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: pywcuhmjbqqlcqhjuldz

class SupabaseConfig {
  static const String supabaseUrl = 'https://pywcuhmjbqqlcqhjuldz.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5d2N1aG1qYnFxbGNxaGp1bGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNDYzOTMsImV4cCI6MjA4NzYyMjM5M30.FayyqyrEBFoFdZi3mKV9md9rqUdEkh8xr0ZiHCf9HXs';
}
