import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

// This function would normally use an AI API key (Gemini/OpenAI)
// Since we don't have the user's key, this is a placeholder structure.
// In a real deployment, you would add:
// const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');

serve(async (req) => {
  // CORS headers
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  }

  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { prompt } = await req.json()

    // Mock AI Generation Logic (Server-side)
    // In production, replace this with actual fetch() to Gemini API
    
    const agentName = prompt.split(' ').slice(0, 2).join('_').toLowerCase().replace(/[^a-z0-9_]/g, '');
    
    const files = {
      'README.md': `# ${agentName} Agent\n\nGenerated by AgentForge.\n\n## Task\n${prompt}\n\n## Usage\nRun \`python main.py\``,
      'main.py': `import os\n\ndef main():\n    print("Running agent for: ${prompt}")\n    # AI Logic would go here\n\nif __name__ == "__main__":\n    main()`,
      'requirements.txt': 'requests\npandas\n'
    };

    return new Response(
      JSON.stringify({ files }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
    )
  }
})
