import 'dart:convert';
import 'dart:typed_data';
// ignore: avoid_web_libraries_in_flutter
import 'dart:html' as html;
import 'package:archive/archive.dart';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

enum GenerationStatus { idle, processing, completed, error }
enum PaymentStatus { unpaid, paid }

class AppState extends ChangeNotifier {
  String _prompt = '';
  GenerationStatus _status = GenerationStatus.idle;
  PaymentStatus _paymentStatus = PaymentStatus.unpaid;
  String? _errorMessage;
  Map<String, String>? _generatedFiles; // filename: content

  String get prompt => _prompt;
  GenerationStatus get status => _status;
  PaymentStatus get paymentStatus => _paymentStatus;
  String? get errorMessage => _errorMessage;
  Map<String, String>? get generatedFiles => _generatedFiles;

  void setPrompt(String value) {
    _prompt = value;
    notifyListeners();
  }

  void reset() {
    _status = GenerationStatus.idle;
    _paymentStatus = PaymentStatus.unpaid;
    _errorMessage = null;
    _generatedFiles = null;
    _prompt = '';
    notifyListeners();
  }

  // Simulate payment for demo purposes
  Future<void> processPayment(String planId) async {
    // In a real app, this would trigger Stripe Checkout via Edge Function
    // and wait for a webhook or return URL.
    _status = GenerationStatus.processing;
    notifyListeners();

    await Future.delayed(const Duration(seconds: 2)); // Simulate network

    _paymentStatus = PaymentStatus.paid;
    _status = GenerationStatus.idle;
    notifyListeners();
  }

  Future<void> generateAgent() async {
    if (_paymentStatus != PaymentStatus.paid) {
      _errorMessage = "Payment required.";
      notifyListeners();
      return;
    }

    _status = GenerationStatus.processing;
    _errorMessage = null;
    notifyListeners();

    try {
      // 1. Try to call Supabase Edge Function (if deployed)
      // 2. Fallback to local mock generation for demo if function fails/not deployed
      
      try {
        final response = await Supabase.instance.client.functions.invoke(
          'generate-agent',
          body: {'prompt': _prompt},
        );
        
        if (response.status == 200) {
           final data = response.data;
           _generatedFiles = Map<String, String>.from(data['files']);
        } else {
          throw Exception('Function error');
        }
      } catch (e) {
        // Fallback: Local Mock Generation
        await Future.delayed(const Duration(seconds: 3)); // Simulate thinking
        _generatedFiles = _mockGenerate(_prompt);
      }

      _status = GenerationStatus.completed;
    } catch (e) {
      _status = GenerationStatus.error;
      _errorMessage = e.toString();
    }

    notifyListeners();
  }

  Map<String, String> _mockGenerate(String prompt) {
    final safePrompt = prompt.replaceAll(RegExp(r'[^a-zA-Z0-9 ]'), '');
    final agentName = safePrompt.split(' ').take(2).join('_').toLowerCase();
    
    return {
      'README.md': '''
# $agentName Agent

Generated by AgentForge.

## Description
This agent is designed to: $prompt

## Setup
1. Install dependencies:
   ```bash
   pip install -r requirements.txt
   ```
2. Run the agent:
   ```bash
   python main.py
   ```

## Privacy
No data was stored during the generation of this agent.
''',
      'requirements.txt': '''
requests
beautifulsoup4
pandas
openai
python-dotenv
''',
      'main.py': '''
import os
import sys
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def main():
    print("Starting $agentName...")
    print("Task: $prompt")
    
    # TODO: Implement core logic here
    # 1. Connect to data source
    # 2. Process data
    # 3. Output results
    
    print("Task completed successfully.")

if __name__ == "__main__":
    main()
''',
      '.env.example': '''
OPENAI_API_KEY=your_key_here
TARGET_URL=https://example.com
'''
    };
  }

  void downloadZip() {
    if (_generatedFiles == null) return;

    final archive = Archive();

    _generatedFiles!.forEach((filename, content) {
      final bytes = utf8.encode(content);
      archive.addFile(ArchiveFile(filename, bytes.length, bytes));
    });

    final zipEncoder = ZipEncoder();
    final encodedArchive = zipEncoder.encode(archive);

    if (encodedArchive == null) return;

    final blob = html.Blob([Uint8List.fromList(encodedArchive)]);
    final url = html.Url.createObjectUrlFromBlob(blob);
    final anchor = html.AnchorElement(href: url)
      ..setAttribute("download", "agent_forge_bundle.zip")
      ..click();
    
    html.Url.revokeObjectUrl(url);
  }
}
